name: homebrew-publish

#run-name: ${{ github.actor }}'s HomeBrew publish

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  homebrew-publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          workdir: ./st3llar
          args: release --clean
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: 'latest'
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_PUBLISHER_TOKEN }}